import type { NextPage } from "next";
import Head from "next/head";
import styles from "./index.module.css";

import {PrismaClient, User} from '@prisma/client'

interface Props {
  users: User[];
}

const prisma = new PrismaClient();

export async function getServerSideProps() {
  const users: User[] = await prisma.user.findMany()
  // console.log(user)
  return {
    props: {
      users
    }
  }
}


const Home: NextPage<Props> = ({users}) => {

  return (
    <>
      <Head>
        <title>prisma + sqlite test</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello!</h1>
      <h1>{users[0]?.name}</h1>
      <h1>{users[0]?.email}</h1>
      
    </>
  );
};

export default Home;


